#!/usr/bin/env bash
#
# Ship one chapter: branch → commit → push → PR link.
#
#   ./scripts/publish-chapter.sh chapters/en/ch01-ai-is-not-a-tool-its-a-species.md
#   ./scripts/publish-chapter.sh --type revise chapters/en/ch01-....md
#   ./scripts/publish-chapter.sh --dry-run chapters/en/ch01-....md
#
# One chapter per branch per PR (see CONTRIBUTING.md). The branch is created from
# main the first time and reused on later runs, so you can push revisions to the
# same PR by running this again.
#
# This script never force-pushes and never touches main directly.

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

commit_type=""
dry_run=false
file=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --type) commit_type="${2:-}"; shift 2 ;;
    --dry-run) dry_run=true; shift ;;
    -h|--help) sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*) echo "Unknown option: $1" >&2; exit 2 ;;
    *) file="$1"; shift ;;
  esac
done

[[ -n "$file" ]] || { echo "Usage: scripts/publish-chapter.sh [--type draft|revise|fix] [--dry-run] <chapter.md>" >&2; exit 2; }
[[ -f "$file" ]] || { echo "No such file: $file" >&2; exit 1; }

step() { printf '\n\033[1m%s\033[0m\n' "$1"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$1"; }
info() { printf '  \033[36m·\033[0m %s\n' "$1"; }
bad()  { printf '  \033[31m✗\033[0m %s\n' "$1"; }

# --- 0. lint ----------------------------------------------------------------
step "1. Lint"
if "$repo_root/scripts/check-chapter.sh" "$file"; then
  ok "chapter passes checks"
else
  bad "chapter failed checks — fix the errors above before publishing"
  echo
  echo "    Re-run with: ./scripts/check-chapter.sh $file"
  exit 1
fi

# --- 1. derive names --------------------------------------------------------
stem="$(basename "$file" .md)"
chapter_tag="${stem%%-*}"          # ch01

title="$(awk 'NR==1 && $0=="---"{inside=1;next} inside && $0=="---"{exit} inside && /^title:/{sub(/^title: */,"");gsub(/^"|"$/,"");print;exit}' "$file")"
[[ -n "$title" ]] || title="$stem"

if git ls-files --error-unmatch "$file" >/dev/null 2>&1; then
  default_type="revise"
else
  default_type="draft"
fi
commit_type="${commit_type:-$default_type}"

branch="draft/${stem}"

step "2. Plan"
info "file    : $file"
info "branch  : $branch"
info "commit  : ${commit_type}(${chapter_tag}): ${title}"

# --- 2. branch state --------------------------------------------------------
current="$(git rev-parse --abbrev-ref HEAD)"
step "3. Branch"
if [[ "$current" == "$branch" ]]; then
  ok "already on $branch"
elif [[ "$current" == "main" || "$current" == "master" ]]; then
  if git show-ref --verify --quiet "refs/heads/$branch"; then
    if $dry_run; then
      info "[dry-run] would switch to existing branch $branch"
    else
      git checkout "$branch"
      ok "switched to existing branch $branch"
    fi
  else
    if $dry_run; then
      info "[dry-run] git checkout -b $branch   (from $current)"
    else
      git checkout -b "$branch"
      ok "created $branch from $current"
    fi
  fi
else
  bad "currently on '$current', which is neither main nor $branch"
  echo
  echo "    Finish or stash that branch first. This script will not move you"
  echo "    off a branch you did not create with it."
  exit 1
fi

# --- 3. stage ---------------------------------------------------------------
step "4. Stage and commit"
$dry_run || git add "$file"
if $dry_run; then
  info "[dry-run] git add $file"
else
  if git diff --cached --quiet; then
    info "nothing staged for $file — already committed?"
  else
    git commit -q -m "${commit_type}(${chapter_tag}): ${title}"
    ok "committed: ${commit_type}(${chapter_tag}): ${title}"
  fi
fi

# --- 4. push ----------------------------------------------------------------
step "5. Push"
if ! git config --get core.sshCommand >/dev/null; then
  bad "core.sshCommand is not configured — run ./scripts/setup-ssh.sh first"
  exit 1
fi

if $dry_run; then
  info "[dry-run] git push -u origin $branch"
else
  git push -u origin "$branch"
  ok "pushed to origin/$branch"
fi

# --- 5. PR link -------------------------------------------------------------
step "6. Open the pull request"
remote_url="$(git remote get-url origin)"
slug="$(sed -E 's#^git@github\.com:##; s#^https://github\.com/##; s#\.git$##' <<<"$remote_url")"
pr_url="https://github.com/${slug}/compare/main...${branch}?expand=1"

echo
echo "  $pr_url"
echo
if [[ -x "$repo_root/scripts/gh.sh" ]] && "$repo_root/scripts/gh.sh" auth status >/dev/null 2>&1; then
  info "gh is authenticated — creating the PR for you:"
  if $dry_run; then
    echo "      gh pr create --base main --head $branch --title \"$title\" --fill"
  elif "$repo_root/scripts/gh.sh" pr create --base main --head "$branch" \
        --title "$title" --body "Draft PR for ${chapter_tag}. Generated by scripts/publish-chapter.sh." ; then
    ok "PR opened"
  else
    info "gh could not open the PR — use the link above"
  fi
else
  info "gh is not authenticated (or not installed) — open the link above."
  echo "      ./scripts/install-gh.sh && ./scripts/gh.sh auth login"
fi
echo
info "merge yourself once it reads right — this is a single-author repo."

# --- 6. remap main note -----------------------------------------------------
if ! $dry_run; then
  step "Next"
  echo "  After merging, get back to a clean main:"
  echo "      git checkout main && git pull && git branch -d $branch"
fi
